// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/company": {
    params: {};
  };
  "/app/contacts": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/app" | "/app/company" | "/app/contacts" | "/app/settings" | "/onboarding";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/company" | "/app/contacts" | "/app/settings";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.company.tsx": {
    id: "routes/app.company";
    page: "/app/company";
  };
  "routes/app.contacts.tsx": {
    id: "routes/app.contacts";
    page: "/app/contacts";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.company": typeof import("./app/routes/app.company.tsx");
  "routes/app.contacts": typeof import("./app/routes/app.contacts.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
};