// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/onboarding";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
};